### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by xiaoshumiao6** [logstash-plugins/logstash-output-influxdb#90]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: logstash-7.8.0-1
- Operating System:CentOS Linux release 7.8.2003
- Config File (if you have sensitive info, please remove it):
- Sample Data:

`{
                 "http_host" => "passport-hz-in.dding.net",
            "request_method" => "GET",
           "upstream_status" => 200,
              "request_time" => 0.003,
    "upstream_response_time" => 0.004,
               "remote_addr" => "192.168.7.8",
                    "status" => 200,
           "body_bytes_sent" => "7519",
                   "request" => "/login"
}
{
                 "http_host" => "passport-hz-in.dding.net",
            "request_method" => "GET",
           "upstream_status" => 200,
              "request_time" => 0.003,
    "upstream_response_time" => 0.0,
               "remote_addr" => "192.168.8.8",
                    "status" => 200,
           "body_bytes_sent" => "7519",
                   "request" => "/login"
}`

> [ERROR] 2020-07-06 22:37:43.900 [[main]>worker1] WorkerLoop - Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
java.lang.NullPointerException: null
	at org.jruby.RubyBasicObject.getMetaClass(RubyBasicObject.java:525) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.pollAndGetClass(InvokeSite.java:725) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:148) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:303) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb) ~[?:?]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:155) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb) ~[?:?]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$block$multi_receive$1(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105) ~[?:?]
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:148) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.Block.yield(Block.java:184) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.RubyArray.each(RubyArray.java:1809) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$method$multi_receive$0(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105) ~[?:?]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:108) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200) ~[jruby-complete-9.2.11.1.jar:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.invokeOutput(OutputStrategyExt.java:148) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$LegacyOutputStrategyExt.output(OutputStrategyExt.java:214) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multiReceive(OutputStrategyExt.java:138) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.OutputDelegatorExt.doOutput(OutputDelegatorExt.java:102) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multiReceive(AbstractOutputDelegatorExt.java:121) ~[logstash-core.jar:?]
	at org.logstash.generated.CompiledDataset3.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset5.compute(Unknown Source) ~[?:?]
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:343) ~[logstash-core.jar:?]
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:333) ~[logstash-core.jar:?]
	at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:83) [logstash-core.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32) [jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.Block.call(Block.java:139) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.RubyProc.call(RubyProc.java:318) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105) [jruby-complete-9.2.11.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
warning: thread "[main]>worker1" terminated with exception (report_on_exception is true):
java.lang.IllegalStateException: java.lang.NullPointerException
	at org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:105)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:441)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:305)
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
	at java.lang.Thread.run(java/lang/Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jruby.RubyBasicObject.getMetaClass(RubyBasicObject.java:525)
	at org.jruby.ir.targets.InvokeSite.pollAndGetClass(InvokeSite.java:725)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:148)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:303)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:155)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$block$multi_receive$1(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:148)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
	at org.jruby.runtime.Block.yield(Block.java:184)
	at org.jruby.RubyArray.each(RubyArray.java:1809)
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$method$multi_receive$0(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:108)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.invokeOutput(OutputStrategyExt.java:148)
	at org.logstash.config.ir.compiler.OutputStrategyExt$LegacyOutputStrategyExt.output(OutputStrategyExt.java:214)
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multiReceive(OutputStrategyExt.java:138)
	at org.logstash.config.ir.compiler.OutputDelegatorExt.doOutput(OutputDelegatorExt.java:102)
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multiReceive(AbstractOutputDelegatorExt.java:121)
	at org.logstash.generated.CompiledDataset3.compute(Unknown Source)
	at org.logstash.generated.CompiledDataset5.compute(Unknown Source)
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:343)
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:333)
	at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32)
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278)
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)
	at org.jruby.runtime.Block.call(Block.java:139)
	at org.jruby.RubyProc.call(RubyProc.java:318)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2020-07-06 22:37:43.895 [[main]>worker0] WorkerLoop - Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
java.lang.NullPointerException: null
	at org.jruby.RubyBasicObject.getMetaClass(RubyBasicObject.java:525) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.pollAndGetClass(InvokeSite.java:725) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:148) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:303) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb) ~[?:?]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:155) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb) ~[?:?]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$block$multi_receive$1(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105) ~[?:?]
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:148) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.Block.yield(Block.java:184) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.RubyArray.each(RubyArray.java:1809) ~[jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$method$multi_receive$0(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105) ~[?:?]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:108) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140) ~[jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200) ~[jruby-complete-9.2.11.1.jar:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.invokeOutput(OutputStrategyExt.java:148) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$LegacyOutputStrategyExt.output(OutputStrategyExt.java:214) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multiReceive(OutputStrategyExt.java:138) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.OutputDelegatorExt.doOutput(OutputDelegatorExt.java:102) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multiReceive(AbstractOutputDelegatorExt.java:121) ~[logstash-core.jar:?]
	at org.logstash.generated.CompiledDataset3.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset5.compute(Unknown Source) ~[?:?]
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:343) ~[logstash-core.jar:?]
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:333) ~[logstash-core.jar:?]
	at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:83) [logstash-core.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:426) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:293) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:24) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:86) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207) [jruby-complete-9.2.11.1.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.runtime.Block.call(Block.java:139) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.RubyProc.call(RubyProc.java:318) [jruby-complete-9.2.11.1.jar:?]
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105) [jruby-complete-9.2.11.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
warning: thread "[main]>worker0" terminated with exception (report_on_exception is true):
java.lang.IllegalStateException: java.lang.NullPointerException
	at org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:105)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:293)
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
	at java.lang.Thread.run(java/lang/Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jruby.RubyBasicObject.getMetaClass(RubyBasicObject.java:525)
	at org.jruby.ir.targets.InvokeSite.pollAndGetClass(InvokeSite.java:725)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:148)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:303)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$timestamp_at_precision$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb:155)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_influxdb_minus_5_dot_0_dot_5.lib.logstash.outputs.influxdb.RUBY$method$receive$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-influxdb-5.0.5/lib/logstash/outputs/influxdb.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$block$multi_receive$1(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:148)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
	at org.jruby.runtime.Block.yield(Block.java:184)
	at org.jruby.RubyArray.each(RubyArray.java:1809)
	at usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.RUBY$method$multi_receive$0(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:105)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:108)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.invokeOutput(OutputStrategyExt.java:148)
	at org.logstash.config.ir.compiler.OutputStrategyExt$LegacyOutputStrategyExt.output(OutputStrategyExt.java:214)
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multiReceive(OutputStrategyExt.java:138)
	at org.logstash.config.ir.compiler.OutputDelegatorExt.doOutput(OutputDelegatorExt.java:102)
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multiReceive(AbstractOutputDelegatorExt.java:121)
	at org.logstash.generated.CompiledDataset3.compute(Unknown Source)
	at org.logstash.generated.CompiledDataset5.compute(Unknown Source)
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:343)
	at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:333)
	at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:426)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:293)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:24)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:86)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278)
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)
	at org.jruby.runtime.Block.call(Block.java:139)
	at org.jruby.RubyProc.call(RubyProc.java:318)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
	at java.lang.Thread.run(Thread.java:748)
[FATAL] 2020-07-06 22:37:44.062 [LogStash::Runner] runner - An unexpected error occurred! {:error=>java.lang.IllegalStateException: java.lang.NullPointerException, :backtrace=>["org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:105)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:441)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:305)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)", "java.lang.Thread.run(java/lang/Thread.java:748)"]}
[ERROR] 2020-07-06 22:37:44.158 [LogStash::Runner] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit

- Steps to Reproduce:

**Comment by xiaoshumiao6** [comment]
Steps to Reproduce::


output {
    influxdb {
        db => "passport"
        host => "localhost"
        allow_time_override => true
        id => "my_plugin_id"
        data_points => {
            "request_time" => "%{request_time}"
            "upstream_response_time" => "%{upstream_response_time}"
            #"request_method" => "%{request_method}"
            #"body_bytes_sent" => "%{body_bytes_sent}"
            #"upstream_status" => "%{upstream_status}"
            #"status" => "%{status}"
            #"uri" => "%{request}"
            #"remote_addr" => "%{remote_addr}"
            #"http_host" => "%{http_host}"
            }
    }
    stdout{
        codec => rubydebug
    }
}
